language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest

branches:
  only:
  - master

before_deploy:
  - zappa package production -o where-release.zip

deploy:
  provider: lambda
  function_name: "where-production"
  region: "us-east-1"
  role: $ROLE_DEPLOY
  handler_name: "lambda_handler"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  runtime: "python3.6"
  module_name: "handler"
  skip_cleanup: true
  zip: where-release.zip
  timeout: 15
  memory_size: 512
